# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Build steps
before_install:
	sudo apt-get install libsdl2-dev libsdl2-net-2.0-0
script:
  - mkdir build
  - cd build
  - cmake .. && make
